jwt:
  private-key: classpath:zzic/jwt/test-private.pem
  public-key: classpath:zzic/jwt/public.pem
  key-id: rsa-key-id
  access-token:
    expiration: 60
    cookie:
      name: access-token
      domain: 
      path: /
      secure: false
      httpOnly: false
      sameSite: none
  refresh-token:
    expiration: 31536000
    cookie:
      name: refresh-token
      domain: 
      path: /
      secure: false
      httpOnly: true
      sameSite: none

spring:
  datasource:
    url: jdbc:h2:file:./data/zzic-db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: debug